streamx.blueprints.json-aggregator.configurations.pim.master-namespace=pim
streamx.blueprints.json-aggregator.configurations.pim.optional-namespaces=price,reviews
streamx.blueprints.json-aggregator.configurations.pim.output-namespace=product

streamx.blueprints.json-aggregator.configurations.reviews.master-namespace=review
streamx.blueprints.json-aggregator.configurations.reviews.output-namespace=reviews

streamx.blueprints.json-aggregator.configurations.categories.master-namespace=cat
streamx.blueprints.json-aggregator.configurations.categories.output-namespace=category

streamx.blueprints.json-aggregator.configurations.puresight-products.master-namespace=puresight_product
streamx.blueprints.json-aggregator.configurations.puresight-products.optional-namespaces=reviews
streamx.blueprints.json-aggregator.configurations.puresight-products.output-namespace=product

streamx.blueprints.json-aggregator.configurations.puresight-categories.master-namespace=puresight_category
streamx.blueprints.json-aggregator.configurations.puresight-categories.output-namespace=category

streamx.blueprints.json-aggregator.configurations.magento-products.master-namespace=default_product
streamx.blueprints.json-aggregator.configurations.magento-products.output-namespace=product

streamx.blueprints.json-aggregator.configurations.magento-categories.master-namespace=default_category
streamx.blueprints.json-aggregator.configurations.magento-categories.output-namespace=category