streamx.proxy.config.subject-regex-rewrite.enabled=true

streamx.proxy.config.subject-regex-rewrite.types.pages.types=com.streamx.blueprints.page.published.v1,com.streamx.blueprints.page.unpublished.v1
streamx.proxy.config.subject-regex-rewrite.types.pages.patterns.config1.match-pattern=^(:?)/published/puresight/pages/(.*)
streamx.proxy.config.subject-regex-rewrite.types.pages.patterns.config1.rewrite-pattern=$1/$2

streamx.proxy.config.subject-regex-rewrite.types.assets.types=com.streamx.blueprints.asset.published.v1,com.streamx.blueprints.asset.unpublished.v1
streamx.proxy.config.subject-regex-rewrite.types.assets.patterns.config1.match-pattern=^(:)?/published/puresight/assets/(.*)
streamx.proxy.config.subject-regex-rewrite.types.assets.patterns.config1.rewrite-pattern=$1/assets/$2

streamx.proxy.config.subject-regex-rewrite.types.eds.types=\
  com.streamx.blueprints.page.published.v1,\
  com.streamx.blueprints.page.unpublished.v1,\
  com.streamx.blueprints.web-resource.published.v1,\
  com.streamx.blueprints.web-resource.unpublished.v1
streamx.proxy.config.subject-regex-rewrite.types.eds.patterns.config1.match-pattern=^(:?)/edge-delivery-services-demo-next/(.*)
streamx.proxy.config.subject-regex-rewrite.types.eds.patterns.config1.rewrite-pattern=$1/edge-delivery-services-demo/$2
