---
global: {}
clusters:
  eu-central-waw-edge:
    enabled: false
    overlay: {}
  eu-south-mil-edge:
    enabled: true
    overlay: {}
  eu-west-par-edge:
    enabled: false
    overlay: {}
  eu-west-par-processing:
    enabled: true
    overlay: {}
  ca-east-bhs-edge:
    enabled: true
    overlay: {}
