clusters.ca-east-bhs-edge.enabled=true
clusters.eu-central-fra-edge.enabled=true
clusters.eu-central-sxb-edge.enabled=true
clusters.eu-central-waw-edge.enabled=true
clusters.eu-south-mil-edge.enabled=true
clusters.eu-west-gra-edge.enabled=true
clusters.eu-west-lon-edge.enabled=true
clusters.eu-west-par-edge.enabled=true
clusters.eu-west-par-processing.enabled=true
clusters.streamx-labs-cn-north-bjs-edge.enabled=true
